---
title: "Bible Verse"
output: html_document
---

A random draw from my list of favourite Bible verses.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(jsonlite)

# send_df_to_js <- function(df){
#   cat(
#     paste(
#     '<script>
#       var data = ',toJSON(df),';
#     </script>'
#     , sep="")
#   )
# }
# 
# #Generate some random x and y data to plot
# n <- 300
# random_data <- data_frame(x = runif(n)*10) %>% 
#   mutate(y = 0.5*x^3 - 1.3*x^2 + rnorm(n, mean = 0, sd = 80),
#          group = paste("group", sample(c(1,2,3), n, replace = T)))
# 
# random_data %>% 
#   head() %>% 
#   send_df_to_js()

```


```{r, results='asis', echo=FALSE}
#Initiate data transfer protocol one
# send_df_to_js(random_data)
```

<button class="btn btn-info btn-sm" id="new-verse">Click to refresh</button>
<br>
<br>
<p id="display-verse">js is not runned. Is it supported in your browser?</p>
<p id="display-verse-ref"></p>

***

A javascript script example with rmarkdown.

To do:

1. Generalise the method to allow for website fetching js var data outside the index.js file

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jsSocials/1.5.0/jssocials.js'></script>

```{js, echo=FALSE}
// background functions

function inIframe () { try { return window.self !== window.top; } catch (e) { return true; } }

function openURL(url){
  window.open(url, 'Share', 'width=550, height=400, toolbar=0, scrollbars=1 ,location=0 ,statusbar=0,menubar=0, resizable=0');
}

var strArray = ["apple", "orange", "juice"];

// json object

var objVerse = {
  "verses":[{"content":"All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness, so that the servant of God may be thoroughly equipped for every good work.","ref":"2 Timothy 3:16-17"},{"content":"Hear, O Israel: The LORD our God, the LORD is one. Love the LORD your God with all your heart and with all your soul and with all your strength.","ref":"Deuteronomy 6:4-5"},{"content":"But he was pierced for our transgressions,<br>he was crushed for our iniquities;<br>the punishment that brought us peace was on him,<br>and by his wounds we are healed.","ref":"Isaiah 53.5"},{"content":"For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.","ref":"John 3:16"},{"content":"The fear of the Lord is the beginning of knowledge,<br>    but fools despise wisdom and instruction.","ref":"Proverbs 1:7"},{"content":"As iron sharpens iron,<br>    so one person sharpens another.","ref":"Proverbs 27:17"},{"content":"The heavens declare the glory of God;<br>    the skies proclaim the work of his hands.<br>Day after day they pour forth speech;<br>    night after night they reveal knowledge.","ref":"Psalm 19:1-2"},{"content":"The Lord is my shepherd, I lack nothing.","ref":"Psalm 23:1"},{"content":"Teach us to number our days, that we may gain a heart of wisdom.","ref":"Psalm 90:12"},{"content":"For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.","ref":"Romans 6:23"},{"content":"And we know that in all things God works for the good of those who love him, who have been called according to his purpose.","ref":"Romans 8:28"},{"content":"I lift up my eyes to the mountains—<br>    where does my help come from?<br>My help comes from the Lord,<br>    the Maker of heaven and earth.","ref":"Psalm 121:1-2"},{"content":"Unless the Lord builds the house,<br>    the builders labor in vain.<br>Unless the Lord watches over the city,<br>    the guards stand watch in vain.","ref":"Psalm 127:1"},{"content":"In their hearts humans plan their course,<br>    but the Lord establishes their steps.","ref":"Proverbs 19:12"},{"content":"He has made everything beautiful in its time. He has also set eternity in the human heart; yet no one can fathom what God has done from beginning to end.","ref":"Ecclesiastes 3:11"}]
};

// specific functions

function randomWholeBetween(a,b) {
  return Math.floor(Math.random() * (b - a + 1) + a);
}

function randomVerse() {
  var rnd = randomWholeBetween(0, objVerse.verses.length);
  return objVerse.verses[rnd].content;
}

// 'meat'
var currentVerse = '';
var currentRef = '';

function getVerse() {
  var rnd = randomWholeBetween(0, objVerse.verses.length);
  //return objVerse.verses[rnd].content;
  
  currentVerse = objVerse.verses[rnd].content;
  currentRef = objVerse.verses[rnd].ref;
  currentTweetURL = 'https://twitter.com/intent/tweet?hashtags=verse&related=bible&text=' + encodeURIComponent('"' + currentVerse + '" ' + currentRef);
  
  $("#display-verse").html(currentVerse);
  $("#display-verse-ref").html(currentRef);
  $("#tweet-verse").attr('href', currentTweetURL);
}

$(document).ready(function () {
  getVerse();
  $("#new-verse").on("click", getVerse);
  //$("#tweet-verse").on("click", function() {
  //  if(!inFrame()) {openURL(currentTweetURL);};});
})
```
